image: docker.io/nixpkgs/nix-flakes

stages:
  - build
  - deploy

build.x86_64-linux.computer-networks-vm:
  stage: build
  script:
    - nix build --option substituters "http://nix-cache.cluster.sesar.int https://cache.nixos.org" --option system-features kvm --print-build-logs .#packages.x86_64-linux.computer-networks-vm
    - mkdir -p build_artifacts/x86-64
    - cp -Lr result build_artifacts/x86-64
  artifacts:
    paths:
      - build_artifacts/
    expire_in: 1 week
  interruptible: true

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r build_artifacts/* public/
  artifacts:
    paths:
      - public
  only:
   - master
